'use stric';

const Helper = require('hubot-test-helper');
const {expect} = require('chai');
const helper = new Helper('../scripts/beneficios.js');

class NewMockResponse extends Helper.Response {
  random(items) {
    return 'Tómate la tarde libre, proletario.';
  };
}

describe('beneficios', function() {
  beforeEach(function() {
    this.room = helper.createRoom({
      response: NewMockResponse
    });
  });
  afterEach(function() {
    this.room.destroy();
  });
  context('Obtener un imagen random', function() {
    beforeEach(function(done) {
      this.room.user.say('user', 'hubot un beneficio');
      setTimeout(done, 500);
    });
    it('Debe entregar una imagen', function() {
      expect(this.room.messages).to.eql([
        ['user', 'hubot un beneficio'],
        ['hubot', 'Tómate la tarde libre, proletario.']
      ]);
    });
  });
});

// ---
// generated by coffee-script 1.9.2
